import { useState } from 'react';
import Modal from "../components/Modal";
import Button from "../components/Button";

function ModalPage() {
  const [showModal, setShowModal] = useState(false);
  
  const handleClick = () => {
    setShowModal(true);
  }

  const handleClose = () => {
    setShowModal(false);
  }

  const actionBar = <div>
    <Button primary onClick={handleClose}>I Accept</Button>
  </div>;

  const modal = <Modal onClose={handleClose} actionBar={actionBar}>
    <p>
      Here is an important agreement to accept.
    </p>
  </Modal>;

  return (
    <div>
      <Button onClick={handleClick} primary>
        Open Modal
      </Button>
      {showModal && modal}
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id scelerisque tortor, eu maximus dolor. Morbi risus lectus, fringilla vel justo a, varius luctus est. Nam pharetra neque at ante mattis pellentesque. Fusce commodo eget tellus a tempus. Aliquam pulvinar, massa maximus faucibus posuere, lorem risus mattis dui, sed tempor mauris risus ut est. In hac habitasse platea dictumst. Sed elit tellus, facilisis in sapien quis, lobortis venenatis dui. Curabitur sit amet ornare velit. Quisque facilisis nisi non erat elementum, a tincidunt massa sodales. Cras lacus nulla, fermentum ut mauris ut, hendrerit condimentum enim. Vestibulum ac viverra ante, luctus elementum elit. Morbi cursus lacus nec urna molestie dictum. Duis finibus tortor sed massa dictum, ac sagittis felis feugiat. Nam vel dolor sed orci faucibus rutrum. Fusce ultricies, nisi at bibendum laoreet, justo odio varius purus, a dictum magna eros nec lorem. Proin bibendum placerat ante, vitae tempor nulla porta et.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id scelerisque tortor, eu maximus dolor. Morbi risus lectus, fringilla vel justo a, varius luctus est. Nam pharetra neque at ante mattis pellentesque. Fusce commodo eget tellus a tempus. Aliquam pulvinar, massa maximus faucibus posuere, lorem risus mattis dui, sed tempor mauris risus ut est. In hac habitasse platea dictumst. Sed elit tellus, facilisis in sapien quis, lobortis venenatis dui. Curabitur sit amet ornare velit. Quisque facilisis nisi non erat elementum, a tincidunt massa sodales. Cras lacus nulla, fermentum ut mauris ut, hendrerit condimentum enim. Vestibulum ac viverra ante, luctus elementum elit. Morbi cursus lacus nec urna molestie dictum. Duis finibus tortor sed massa dictum, ac sagittis felis feugiat. Nam vel dolor sed orci faucibus rutrum. Fusce ultricies, nisi at bibendum laoreet, justo odio varius purus, a dictum magna eros nec lorem. Proin bibendum placerat ante, vitae tempor nulla porta et.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id scelerisque tortor, eu maximus dolor. Morbi risus lectus, fringilla vel justo a, varius luctus est. Nam pharetra neque at ante mattis pellentesque. Fusce commodo eget tellus a tempus. Aliquam pulvinar, massa maximus faucibus posuere, lorem risus mattis dui, sed tempor mauris risus ut est. In hac habitasse platea dictumst. Sed elit tellus, facilisis in sapien quis, lobortis venenatis dui. Curabitur sit amet ornare velit. Quisque facilisis nisi non erat elementum, a tincidunt massa sodales. Cras lacus nulla, fermentum ut mauris ut, hendrerit condimentum enim. Vestibulum ac viverra ante, luctus elementum elit. Morbi cursus lacus nec urna molestie dictum. Duis finibus tortor sed massa dictum, ac sagittis felis feugiat. Nam vel dolor sed orci faucibus rutrum. Fusce ultricies, nisi at bibendum laoreet, justo odio varius purus, a dictum magna eros nec lorem. Proin bibendum placerat ante, vitae tempor nulla porta et.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id scelerisque tortor, eu maximus dolor. Morbi risus lectus, fringilla vel justo a, varius luctus est. Nam pharetra neque at ante mattis pellentesque. Fusce commodo eget tellus a tempus. Aliquam pulvinar, massa maximus faucibus posuere, lorem risus mattis dui, sed tempor mauris risus ut est. In hac habitasse platea dictumst. Sed elit tellus, facilisis in sapien quis, lobortis venenatis dui. Curabitur sit amet ornare velit. Quisque facilisis nisi non erat elementum, a tincidunt massa sodales. Cras lacus nulla, fermentum ut mauris ut, hendrerit condimentum enim. Vestibulum ac viverra ante, luctus elementum elit. Morbi cursus lacus nec urna molestie dictum. Duis finibus tortor sed massa dictum, ac sagittis felis feugiat. Nam vel dolor sed orci faucibus rutrum. Fusce ultricies, nisi at bibendum laoreet, justo odio varius purus, a dictum magna eros nec lorem. Proin bibendum placerat ante, vitae tempor nulla porta et.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id scelerisque tortor, eu maximus dolor. Morbi risus lectus, fringilla vel justo a, varius luctus est. Nam pharetra neque at ante mattis pellentesque. Fusce commodo eget tellus a tempus. Aliquam pulvinar, massa maximus faucibus posuere, lorem risus mattis dui, sed tempor mauris risus ut est. In hac habitasse platea dictumst. Sed elit tellus, facilisis in sapien quis, lobortis venenatis dui. Curabitur sit amet ornare velit. Quisque facilisis nisi non erat elementum, a tincidunt massa sodales. Cras lacus nulla, fermentum ut mauris ut, hendrerit condimentum enim. Vestibulum ac viverra ante, luctus elementum elit. Morbi cursus lacus nec urna molestie dictum. Duis finibus tortor sed massa dictum, ac sagittis felis feugiat. Nam vel dolor sed orci faucibus rutrum. Fusce ultricies, nisi at bibendum laoreet, justo odio varius purus, a dictum magna eros nec lorem. Proin bibendum placerat ante, vitae tempor nulla porta et.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id scelerisque tortor, eu maximus dolor. Morbi risus lectus, fringilla vel justo a, varius luctus est. Nam pharetra neque at ante mattis pellentesque. Fusce commodo eget tellus a tempus. Aliquam pulvinar, massa maximus faucibus posuere, lorem risus mattis dui, sed tempor mauris risus ut est. In hac habitasse platea dictumst. Sed elit tellus, facilisis in sapien quis, lobortis venenatis dui. Curabitur sit amet ornare velit. Quisque facilisis nisi non erat elementum, a tincidunt massa sodales. Cras lacus nulla, fermentum ut mauris ut, hendrerit condimentum enim. Vestibulum ac viverra ante, luctus elementum elit. Morbi cursus lacus nec urna molestie dictum. Duis finibus tortor sed massa dictum, ac sagittis felis feugiat. Nam vel dolor sed orci faucibus rutrum. Fusce ultricies, nisi at bibendum laoreet, justo odio varius purus, a dictum magna eros nec lorem. Proin bibendum placerat ante, vitae tempor nulla porta et.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id scelerisque tortor, eu maximus dolor. Morbi risus lectus, fringilla vel justo a, varius luctus est. Nam pharetra neque at ante mattis pellentesque. Fusce commodo eget tellus a tempus. Aliquam pulvinar, massa maximus faucibus posuere, lorem risus mattis dui, sed tempor mauris risus ut est. In hac habitasse platea dictumst. Sed elit tellus, facilisis in sapien quis, lobortis venenatis dui. Curabitur sit amet ornare velit. Quisque facilisis nisi non erat elementum, a tincidunt massa sodales. Cras lacus nulla, fermentum ut mauris ut, hendrerit condimentum enim. Vestibulum ac viverra ante, luctus elementum elit. Morbi cursus lacus nec urna molestie dictum. Duis finibus tortor sed massa dictum, ac sagittis felis feugiat. Nam vel dolor sed orci faucibus rutrum. Fusce ultricies, nisi at bibendum laoreet, justo odio varius purus, a dictum magna eros nec lorem. Proin bibendum placerat ante, vitae tempor nulla porta et.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id scelerisque tortor, eu maximus dolor. Morbi risus lectus, fringilla vel justo a, varius luctus est. Nam pharetra neque at ante mattis pellentesque. Fusce commodo eget tellus a tempus. Aliquam pulvinar, massa maximus faucibus posuere, lorem risus mattis dui, sed tempor mauris risus ut est. In hac habitasse platea dictumst. Sed elit tellus, facilisis in sapien quis, lobortis venenatis dui. Curabitur sit amet ornare velit. Quisque facilisis nisi non erat elementum, a tincidunt massa sodales. Cras lacus nulla, fermentum ut mauris ut, hendrerit condimentum enim. Vestibulum ac viverra ante, luctus elementum elit. Morbi cursus lacus nec urna molestie dictum. Duis finibus tortor sed massa dictum, ac sagittis felis feugiat. Nam vel dolor sed orci faucibus rutrum. Fusce ultricies, nisi at bibendum laoreet, justo odio varius purus, a dictum magna eros nec lorem. Proin bibendum placerat ante, vitae tempor nulla porta et.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id scelerisque tortor, eu maximus dolor. Morbi risus lectus, fringilla vel justo a, varius luctus est. Nam pharetra neque at ante mattis pellentesque. Fusce commodo eget tellus a tempus. Aliquam pulvinar, massa maximus faucibus posuere, lorem risus mattis dui, sed tempor mauris risus ut est. In hac habitasse platea dictumst. Sed elit tellus, facilisis in sapien quis, lobortis venenatis dui. Curabitur sit amet ornare velit. Quisque facilisis nisi non erat elementum, a tincidunt massa sodales. Cras lacus nulla, fermentum ut mauris ut, hendrerit condimentum enim. Vestibulum ac viverra ante, luctus elementum elit. Morbi cursus lacus nec urna molestie dictum. Duis finibus tortor sed massa dictum, ac sagittis felis feugiat. Nam vel dolor sed orci faucibus rutrum. Fusce ultricies, nisi at bibendum laoreet, justo odio varius purus, a dictum magna eros nec lorem. Proin bibendum placerat ante, vitae tempor nulla porta et.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id scelerisque tortor, eu maximus dolor. Morbi risus lectus, fringilla vel justo a, varius luctus est. Nam pharetra neque at ante mattis pellentesque. Fusce commodo eget tellus a tempus. Aliquam pulvinar, massa maximus faucibus posuere, lorem risus mattis dui, sed tempor mauris risus ut est. In hac habitasse platea dictumst. Sed elit tellus, facilisis in sapien quis, lobortis venenatis dui. Curabitur sit amet ornare velit. Quisque facilisis nisi non erat elementum, a tincidunt massa sodales. Cras lacus nulla, fermentum ut mauris ut, hendrerit condimentum enim. Vestibulum ac viverra ante, luctus elementum elit. Morbi cursus lacus nec urna molestie dictum. Duis finibus tortor sed massa dictum, ac sagittis felis feugiat. Nam vel dolor sed orci faucibus rutrum. Fusce ultricies, nisi at bibendum laoreet, justo odio varius purus, a dictum magna eros nec lorem. Proin bibendum placerat ante, vitae tempor nulla porta et.</p>
    </div>
  );
}

export default ModalPage;